lanches = ('hambúrguer', 'suco', 'refri', 'pudim')
print(lanches[2])# VAI MOSTRAR O REFRI, POIS EM PYTHON SE COMEÇA COM 0
print(lanches[0])# VAI MOSTRAR O HAMBÚRGUER
print(lanches[::])# O PRIMEIRO TERMO É O ÍNDECE/ O SEGUNDO É ATÉ ONDE VAI/ O TERCEIRO É DE QUANTAS CASAS VAI PULAR
print(lanches[:2:2])# COMEÇA DO PRIMEIRO TERMO, VAI ATÉ O TERCEIRO E VAI PULANDO 2 CASAS
print(lanches[-1])# VAI PEGAR O ULTIMO TERMO
print(lanches[-2:])# VAI COMEÇAR DO PENÚLTIMO TERMO ATÉ O ULTIMO
print(lanches[-4::2])# VAI COMEÇAR DO PRIMEIRO TERMO, ATÉ O ULTIMO, PULANDO 2 CASA

# NÃO É POSSIVÉL TROCAR UM TERMO DE UMA TUPLA
# AS TUPLAS  SÃO IMUTÁVEIS
# SE TENTARMOS TROCAR O VALOR VAI  ( lanches[3] = 'sorvete' ) DAR ERRO 