import math
# O MATH É UM MÓDULO QUE JÁ VEM NO PYTHON E QUE ADICIONA MAIS ALGUMAS OPERAÇÃO MATEMÁTICA
# PARA IMPORTA O MATH ULTILIZAMOS O IMPORT NO COMEÇO DO PROGAMA

# O MATH TEM ALGUMAS FUÇÕES COMO 
raiz = math.sqrt(7) # QUE CALCULA A RAIZ QUADRADA COM isqrt() ELE RETORNA A RAIZ INTEIRA
math.sin(60) # RETORNA O SENO DE UM NÚMERO
math.cos(30) # RETORNA O COSENO DE UM NÚMERO
math.radians(45)  # RETORNA O ÂNGULO EM GRAUS
math.ceil(2.5648) # ARREDONDA PARA O MAIOR, MENOR OU IGUAL

print(f'A raiz quadrada é {raiz}')